### ISSUE TITLE
Getting the credentials

### ISSUE THREAD

**Issue by kamal-hossain** [shahriar-shojib/React-bKash#1]
How can I get the `createPaymentURL` & `executePaymentURL` ?
Is there specific documentation link for getting and using those values?

thanks in advance.

**Comment by sonjoydatta** [comment]
It will come from your backend API. To understand how to implement bKash on your backend see this library, https://github.com/shahriar-shojib/bkash-payment-gateway

Docs @ #2

**Comment by kamal-hossain** [comment]
This thing seems like very confusing to me. Do you guys know how to use [sslcommerz](https://www.sslcommerz.com/payment-gateway/ ) in react?
