### ISSUE TITLE
Unhandled Rejection (ReferenceError): bKash is not defined

### ISSUE THREAD

**Issue by ishtiaqmahmood** [shahriar-shojib/React-bKash#10]
![Screenshot from 2022-01-04 09-36-37](https://user-images.githubusercontent.com/22867601/148006322-7ec96d2c-a6b7-470d-a85f-bbdbff039832.png)

**Comment by shahriar-shojib** [comment]
![image](https://user-images.githubusercontent.com/6505094/148033373-141bea43-17d9-49a7-920c-5f038821b569.png)
This is not a valid url for bkash script, please note that in the README, we only provided a dummy URL and if you have proper bkash credentials, they should send you this URL as well.
