### ISSUE TITLE
Unhandled Rejection (ReferenceError): bKash is not defined

### ISSUE THREAD

**Issue by asmaul555** [shahriar-shojib/React-bKash#11]
initBkash
G:/AllProject/amazon-project/src/utils/initBkash.ts:47

 button.style.display = 'none';
  45 | button.id = 'bKash_button';
  46 | const body = document.querySelector('body');
> 47 | if (body) {
     | ^  48 |     body.appendChild(button);
  49 |     return;
  50 | }

**Comment by shahriar-shojib** [comment]
Can you include the props that you sent to the BkashButton component?
