### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Yadab-Sd** [shahriar-shojib/React-bKash#17]
I don't know why I'm getting this error. Please help!

**Comment by shahriar-shojib** [comment]
Are you using create react app?

**Comment by Yadab-Sd** [comment]
yes




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/27/22,
11:43:32 PM

**Comment by shahriar-shojib** [comment]
Hello,
I was able to create a payment without any issues.
Try upgrading to latest version.
Checkout this codeSandbox for example: https://codesandbox.io/s/fast-water-z79gm6?file=/src/App.tsx
