### ISSUE TITLE
Default condition should be last one

### ISSUE THREAD

**Issue by JoniSutradhor** [shahriar-shojib/React-bKash#20]
ERROR in ./src/App.tsx 7:0-42
Module not found: Error: Default condition should be last one
 @ ./src/index.tsx 7:0-32 11:33-40

on custom API implementation.

Getting this error,
any solution please......

**Comment by shahriar-shojib** [comment]
Seems like an issue with package.json exports field @sonjoydatta can you help?

**Comment by shahriar-shojib** [comment]
I have released a new version 2.0.5 with #21 hopefully this will fix your issue, if not check if your bundler supports commonjs imports
